services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"   
      - "15672:15672"   
      - "15692:15692"
    command: >
      bash -c "rabbitmq-plugins enable --offline rabbitmq_prometheus && rabbitmq-server"
    hostname: rabbitmq
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - mspr4-network
      - metrics
    

  produit:
    image: genessy/epsi4a-mspr4-msproduct:0.4.5
    container_name: produit
    hostname: produit
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3022:3022"
    env_file:
      - ./envs/.env.dockercompose.product
    volumes:
      - ./serviceAccountKey.json:/app/credentials/serviceAccountKey.json
      - ./logs:/app/logs
    networks:
      - mspr4-network
      - elk
      - metrics
    
  client:
    image: antoineletailleur/epsi4a-mspr4-msclient:0.4
    container_name: client
    hostname: client
    depends_on:
      rabbitmq:
        condition: service_healthy
    ports:
      - "3033:3033"
      - "3013:3013"
    env_file:
      - ./envs/.env.dockercompose.client
    networks:
      - mspr4-network
      - elk
      - metrics

  # fidelite:
  #   image: gmeline/epsi4a-mspr4-msfidelity:0.3
  #   container_name: fidelite
  #   hostname: fidelite
  #   depends_on:
  #     rabbitmq:
  #       condition: service_healthy
  #   platform: linux/arm64
  #   ports:
  #     - "3044:8080"
  #   networks:
  #     - mspr4-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.3
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: docker.elastic.co/logstash/logstash:7.9.3
    volumes:
      - ./logstash/pipeline:/usr/share/logstash/pipeline
    ports:
      - "5000:5000"
      - "5044:5044"
    networks:
      - elk

  kibana:
    image: docker.elastic.co/kibana/kibana:7.9.3
    ports:
      - "5601:5601"
    networks:
      - elk

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - metrics

  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - "3000:3000"
    networks:
      - metrics
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus

networks:
  mspr4-network:
    driver: bridge
  elk:
    driver: bridge
  metrics:
    driver: bridge