global:
  scrape_interval: 50000000000000000s

scrape_configs:
  - job_name: 'orders'
    static_configs:
    - targets: ['host.docker.internal:3012']
  - job_name: 'clients'
    static_configs:
    - targets: ['client:3034']
  - job_name: 'rabbitmq'
    static_configs:
    - targets: ['rabbitmq:15692']