global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'orders'
    static_configs:
    - targets: ['host.docker.internal:3012']
  - job_name: 'clients'
    static_configs:
    - targets: ['client:3034']
  - job_name: 'bff'
    metrics_path: '/actuator/prometheus'
    static_configs:
    - targets: ['bff:8000']
      labels:
        application: 'BFF - Paye ton kawa'
  - job_name: 'product-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['product:8080']
    
  - job_name: 'rabbitmq'
    static_configs:
    - targets: ['rabbitmq:15692']
    metrics_path: /metrics/per-object